# Generated by Django 2.2.6 on 2019-10-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='50f219ff-57e4-45fc-ad30-b0e68a9ccd25', editable=False, max_length=36, unique=True)),
                ('comic', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('url', models.TextField()),
                ('description', models.CharField(max_length=512)),
                ('rewards', models.SmallIntegerField()),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ComicsUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('url', models.TextField()),
                ('index', models.SmallIntegerField()),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics_url', to='comics.Comic')),
            ],
        ),
    ]
